config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'rooms#index'
  resources :users, only: :show
  resources :rooms do
    resources :comments, only: %i[create destroy]
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :text, presence: true
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: '北海道' }, { id: 3, name: '青森県' }, { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' }, { id: 7, name: '山形県' },
    { id: 8, name: '福島県' }, { id: 9, name: '茨城県' }, { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' }, { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' }, { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' }, { id: 18, name: '石川県' }, { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' }, { id: 21, name: '長野県' }, { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' }, { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' }, { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' }, { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' }, { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' }, { id: 36, name: '山口県' }, { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' }, { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' }, { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' }, { id: 45, name: '大分県' }, { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :user
  has_many :room
end

app/models/room.rb
class Room < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture

  validates :room_name, :municipalities, presence: true
  validates :prefecture_id, numericality: { other_than: 1, message: 'Select' }
  belongs_to :user
  has_many :comments, dependent: :destroy

  def self.search(search)
    if search != ''
      Room.where('room_name LIKE(?)', "%#{search}%")
    else
      Room.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture

  validates :profile, :name, presence: true
  validates :prefecture_id, numericality: { other_than: 1, message: 'Select' }
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください'

  has_many :rooms
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name phone_number profile prefecture_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    room = Room.find(params[:room_id])
    @comment = room.comments.new(comment_params)
    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    comment = Comment.find(params[:room_id])
    text = comment.user.id
    if comment.user_id == current_user.id
      comment.destroy
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, room_id: params[:room_id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :search]
  before_action :set_one, only: %i[edit show update destroy]
  before_action :set_transition, only: [:edit, :update, :destroy]

  def index
    @rooms = Room.all.order(created_at: 'DESC')
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to action: :index
  end

  def edit
  end

  def show
    @comment = Comment.new
    @comments = @room.comments.includes(:user)
  end

  def search
    @rooms = Room.search(params[:keyword])
  end

  def update
    if @room.update(room_params)
      redirect_to action: :index
    else
      reder :edit
    end
  end

  private

  def room_params
    params.require(:room).permit(:room_name, :prefecture_id, :host_date,
                                 :municipalities).merge(user_id: current_user.id)
  end

  def set_one
    @room = Room.find(params[:id])
  end

  def set_transition
    unless current_user.id == @room.user_id
      redirect_to action: :index
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :index

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OriginalApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name = "viewport" content="width=device-width,initial-scale=1.0" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="footer-fixed">
      <header class="header">
        <div class="inner">
          <div class="nav">
            <div class="nav_left">
              <%= link_to image_tag("/assets/soccer-league-header-or-banner-design-with-soccer-ball_1302-18062.jpg", class: :logo), root_path %>
            </div>
            <% if user_signed_in? %>
              <div class="nav_right">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav_btn %>
                <%= link_to "メンバー募集", new_room_path, class: :nav_btn %>
              </div>
            <% else %>
              <div class="nav_right">
                <%= link_to "ログイン", user_session_path, class: :nav_btn %>
                <%= link_to "新規登録", new_user_registration_path, class: :nav_btn %>
              </div>
            <% end %>
          </div>
        </div>
      </header>
      <%= yield %>
      <footer class="footer">
        <p class="content">Lets'enjoy</p>
      </footer>
    </div>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with model: room, local: true do |f| %>

  <div class="field">
    <%= f.label :room_name, "ルーム名" %><br>
    <%= f.text_field :room_name %>
  </div>

  <div class="field">
    <%= f.label :host_date, "主催日と日時" %><br>
    <%= f.datetime_select :host_date, class: 'form-control'%>
  </div>

  <div class="field">
    <%= f.label :prefecture_id, "主催地" %><br />
    <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %>
  </div>

  <div class="field">
    <%= f.label :municipalities, "主催地(市町村)" %><br />
    <%= f.text_field :municipalities, autofocus: true, autocomplete: "municipalities" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>

  <div class="image-center">
    <img src="/assets/9cf9abf6.png" class="move-image animation">
  </div>
<% end %>

app/views/rooms/_pull.html.erb
<ul class="more_lists">
  <% if user_signed_in? %>
    <% if current_user.id == room.user_id %>
      <li class="more_list">
        <%= link_to '編集', edit_room_path(room.id), class: :more_list %>
        <%= link_to '削除', room_path(room.id), method: :delete, data: {confirm: "削除しますか？"}, class: :more_list %>
      </li>
    <% end %>
    <li class="more_list">
      <%= link_to 'コメント', room_path(room.id), class: :more_list %>
    </li>
  <% end %>
</ul>

app/views/rooms/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form_wrapper">
      <%= render partial: "form", locals: { room: @room } %>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="main-wrappers">
  <h1 class="main-title">ルーム一覧</h1>
  <%= form_with(url: search_rooms_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "ルームを検索する", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>
  <div class="inner">
    <div class="room_wrapper">
      <% @rooms.each do |room| %>
        <div class="room">
          <div class="room-name">
            主催者: <%= link_to room.user.name, user_path(room.user.id), class: "room-none" %>
          </div>
          <div class="room-name">
            ルーム名: <%= room.room_name %>
          </div>
          <div class="room-name">
            主催場所: <%= room.prefecture.name %>、<%= room.municipalities %>
          </div>
          <div class="room-host-date">
            集合日時: <%= room.host_date.strftime("%Y年%-m月%-d日 %-H時%-M分") %>
          </div>
          <%= render partial: "pull", locals: { room: room } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form_wrapper">
      <%= render partial: "form", locals: { room: @room } %>
    </div>
  </div>
</div>

app/views/rooms/search.html.erb
<div class="main-wrappers">
  <h1 class="main-title">ルーム一覧</h1>
  <%= form_with(url: search_rooms_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "ルームを検索する", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>
  <div class="inner">
    <div class="room_wrapper">
      <% @rooms.each do |room| %>
        <div class="room">
          <div class="room-name">
            主催者: <%= link_to room.user.name, user_path(room.user.id), class: "room-none" %>
          </div>
          <div class="room-name">
            ルーム名: <%= room.room_name %>
          </div>
          <div class="room-name">
            主催場所: <%= room.prefecture.name %>、<%= room.municipalities %>
          </div>
          <div class="room-host-date">
            集合日時: <%= room.host_date.strftime("%Y年%-m月%-d日 %-H時%-M分") %>
          </div>
          <%= render partial: "pull", locals: { room: room } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="comment-image">
  <div class="footer-fixed">
    <div class="inner">
      <div class="room-title-name">ルーム名
        <%= @room.room_name %>
      </div>
      <div class="comments" id="comment_btn">
        <% @comments.each do |comment| %>
          <% if comment.user_id == current_user.id %>
            <div class="right-comment">
              <%= link_to " ","/users/#{comment.user_id}" %>
              <div class="comment-chat">
                <%= link_to image_tag("ごみ箱のフリーアイコン.png"), room_comment_path(comment.id), method: :delete, class: "hidden-comment" %>
                <%= comment.text %>
                <%= l comment.created_at %>
              </div>
            </div>
          <% else %>
            <div class="left-comment">
              <%= link_to comment.user.name, "/users/#{comment.user_id}" %>
              <div class="comment-chat">
                <%= comment.text %>
                <%= l comment.created_at %>
              </div>
            </div>
          <% end %>
        <% end %>
        <%= form_with model: [@room, @comment], class: 'comment-form', local: true do |f| %>
          <div class="comment-from">
              <%= f.text_field :text, autofocus: true, class: 'form-message', placeholder: 'コメントする' %>
              <%= f.submit '送信',id: "submit_btn", class: 'form-submit' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-wrapper">
  <div class="room-user-name">
    <%= @user.name%>さんの情報
  </div>
  <table class="detail-table">
    <tbody>
      <tr>
        <th class="detail-item">投稿者</th>
        <td class="detail-value"><%= @user.name %></td>
      </tr>
      <tr>
        <th class="detail-item">メールアドレス</th>
        <td class="detail-value"><%= @user.email %></td>
      </tr>
      <% if @user.phone_number.present? %>
        <tr>
          <th class="detail-item">電話番号</th>
          <td class="detail-value"><%= @user.phone_number %></td>
        </tr>
      <% else %>
      <tr>
          <th class="detail-item">電話番号</th>
          <td class="detail-value">※※※※</td>
        </tr>
      <% end %>
      <tr>
        <th class="detail-item">出身地</th>
        <td class="detail-value"><%= @user.prefecture.name %></td>
      </tr>
      <tr>
        <th class="detail-item">プロフィール</th>
        <td class="detail-value"><%= @user.profile %></td>
      </tr>
    </tbody>
  </table>
</div>